site_name: REL-ÉLECTRONIQUE POUR ESPACES IMMERSIFS
site_description: 'Ressource éducative libre (REL) sur l'intégration de l'électronique aux espaces immersifs'
site_author: 'Thomas O Fredericks et Guillaume Arseneault'
docs_dir: docs/
repo_name: 'tim-montmorency/rel-electro-immersif'
repo_url: 'https://github.com/tim-montmorency/rel-electro-immersif'
nav:
    - Home: index.md
theme:
  name: 'material'
